using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Frozen;
using FindUnused;

namespace FindUnused.Tests;

[TestClass]
public class ConfigurationTests
{
    [TestMethod]
    public void AnalyzerConfiguration_DefaultValues_AreCorrect()
    {
        var config = new AnalyzerConfiguration();

        Assert.IsTrue(config.IncludePublicSymbols);
        Assert.IsTrue(config.IncludeInternalSymbols);
        Assert.IsTrue(config.ExcludeGeneratedCode);
        Assert.AreEqual("loose", config.AnalysisMode);
        Assert.IsFalse(config.DetectDeadCode);
        Assert.IsFalse(config.DetectTodoComments);
    }

    [TestMethod]
    public void AnalyzerConfiguration_ExclusionPatterns_ContainsExpectedPatterns()
    {
        var config = new AnalyzerConfiguration();

        Assert.IsTrue(config.ExclusionPatterns.Contains("/.nuget/packages/"));
        Assert.IsTrue(config.ExclusionPatterns.Contains("/.nuget/"));
        Assert.IsTrue(config.ExclusionPatterns.Contains("/packages/"));
        Assert.IsTrue(config.ExclusionPatterns.Contains("/bin/"));
        Assert.IsTrue(config.ExclusionPatterns.Contains("/obj/"));
        Assert.IsTrue(config.ExclusionPatterns.Contains("/debug/"));
        Assert.IsTrue(config.ExclusionPatterns.Contains("/release/"));
        Assert.AreEqual(7, config.ExclusionPatterns.Count);
    }

    [TestMethod]
    public void AnalyzerConfiguration_GeneratedCodeMarkers_ContainsExpectedMarkers()
    {
        var config = new AnalyzerConfiguration();

        Assert.IsTrue(config.GeneratedCodeMarkers.Contains("<auto-generated"));
        Assert.IsTrue(config.GeneratedCodeMarkers.Contains("generated by"));
        Assert.IsTrue(config.GeneratedCodeMarkers.Contains("<autogenerated"));
        Assert.IsTrue(config.GeneratedCodeMarkers.Contains("// <auto-generated"));
        Assert.IsTrue(config.GeneratedCodeMarkers.Contains("[GeneratedCode]"));
        Assert.IsTrue(config.GeneratedCodeMarkers.Contains("@generated"));
        Assert.IsTrue(config.GeneratedCodeMarkers.Contains("[CompilerGenerated]"));
    }

    [TestMethod]
    public void AnalyzerConfiguration_TestAttributes_ContainsExpectedAttributes()
    {
        var config = new AnalyzerConfiguration();

        Assert.IsTrue(config.TestAttributes.Contains("TestAttribute"));
        Assert.IsTrue(config.TestAttributes.Contains("FactAttribute"));
        Assert.IsTrue(config.TestAttributes.Contains("TheoryAttribute"));
        Assert.IsTrue(config.TestAttributes.Contains("TestMethodAttribute"));
        Assert.IsTrue(config.TestAttributes.Contains("TestCaseAttribute"));
        Assert.IsTrue(config.TestAttributes.Contains("TestCaseSourceAttribute"));
        Assert.IsTrue(config.TestAttributes.Contains("InlineDataAttribute"));
        Assert.IsTrue(config.TestAttributes.Contains("ClassDataAttribute"));
        Assert.IsTrue(config.TestAttributes.Contains("DynamicDataAttribute"));
    }

    [TestMethod]
    public void AnalyzerConfiguration_TestClassAttributes_ContainsExpectedAttributes()
    {
        var config = new AnalyzerConfiguration();

        Assert.IsTrue(config.TestClassAttributes.Contains("TestClassAttribute"));
        Assert.IsTrue(config.TestClassAttributes.Contains("TestFixtureAttribute"));
        Assert.IsTrue(config.TestClassAttributes.Contains("TestCategoryAttribute"));
    }

    [TestMethod]
    public void AnalyzerConfiguration_ExclusionPatterns_IsCaseInsensitive()
    {
        var config = new AnalyzerConfiguration();

        Assert.IsTrue(config.ExclusionPatterns.Contains("/BIN/"));
        Assert.IsTrue(config.ExclusionPatterns.Contains("/Bin/"));
    }

    [TestMethod]
    public void AnalyzerConfiguration_GeneratedCodeMarkers_IsCaseInsensitive()
    {
        var config = new AnalyzerConfiguration();

        Assert.IsTrue(config.GeneratedCodeMarkers.Contains("[GENERATEDCODE]"));
        Assert.IsTrue(config.GeneratedCodeMarkers.Contains("[CompilerGenerated]"));
    }

    [TestMethod]
    public void AnalyzerCache_WhenCreatedWithoutConfig_UsesDefaultConfiguration()
    {
        var cache = new AnalyzerCache();

        Assert.IsNotNull(cache.ExclusionPatterns);
        Assert.IsNotNull(cache.GeneratedCodeMarkers);
        Assert.IsNotNull(cache.TestAttributes);
        Assert.IsNotNull(cache.TestClassAttributes);
        Assert.AreEqual(7, cache.ExclusionPatterns.Count);
    }

    [TestMethod]
    public void AnalyzerCache_WhenCreatedWithConfig_UsesProvidedConfiguration()
    {
        var config = new AnalyzerConfiguration
        {
            IncludePublicSymbols = false,
            AnalysisMode = "strict"
        };
        var cache = new AnalyzerCache(config);

        Assert.IsNotNull(cache.ExclusionPatterns);
        Assert.IsNotNull(cache.GeneratedCodeMarkers);
    }

    [TestMethod]
    public void AnalyzerCache_ExclusionPatterns_IsImmutableFrozenSet()
    {
        var cache = new AnalyzerCache();

        Assert.IsInstanceOfType(cache.ExclusionPatterns, typeof(FrozenSet<string>));
    }
}
