using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Text.Json;
using FindUnused;

namespace FindUnused.Tests;

[TestClass]
public class FunctionalTests
{
    private static readonly string s_testRoot = Path.Combine(Path.GetTempPath(), "FindUnusedFunctionalTests");

    [TestInitialize]
    public void Setup()
    {
        Directory.CreateDirectory(s_testRoot);
    }

    [TestCleanup]
    public void Cleanup()
    {
        if (Directory.Exists(s_testRoot))
        {
            try
            {
                Directory.Delete(s_testRoot, recursive: true);
            }
            catch { }
        }
    }

    [TestMethod]
    public async Task RunAsync_WithMissingTarget_ReturnsExitCodeOne()
    {
        int exitCode = await Program.RunAsync([]);

        Assert.AreEqual(1, exitCode);
    }

    [TestMethod]
    public async Task RunAsync_WithInvalidTarget_ReturnsExitCodeOne()
    {
        int exitCode = await Program.RunAsync(["--target", "/nonexistent/path.sln"]);

        Assert.AreEqual(1, exitCode);
    }

    [TestMethod]
    public async Task RunAsync_WithValidTarget_ReturnsSuccess()
    {
        string projectDir = CreateTestProject("""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>
            </Project>
            """, """
            public class MyClass {
                private void UnusedMethod() { }
                public void UsedMethod() { }
            }
            public class Program {
                public static void Main() {
                    var c = new MyClass();
                    c.UsedMethod();
                }
            }
            """);

        int exitCode = await Program.RunAsync(["--target", projectDir]);

        Assert.AreEqual(0, exitCode);
    }

    [TestMethod]
    public async Task RunAsync_WithExcludePublic_ReturnsSuccess()
    {
        string projectDir = CreateTestProject("""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>
            </Project>
            """, """
            public class MyClass {
                public void UnusedPublicMethod() { }
                private void UsedPrivateMethod() { }
            }
            public class Program {
                public static void Main() {
                    var c = new MyClass();
                    c.UsedPrivateMethod();
                }
            }
            """);

        int exitCode = await Program.RunAsync(["--target", projectDir, "--exclude-public"]);

        Assert.AreEqual(0, exitCode);
    }

    [TestMethod]
    public async Task RunAsync_WithStrictMode_ReturnsSuccess()
    {
        string projectDir = CreateTestProject("""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>
            </Project>
            """, """
            public class MyClass {
                public void UnusedPublicMethod() { }
            }
            """);

        int exitCode = await Program.RunAsync(["--target", projectDir, "--strict"]);

        Assert.AreEqual(0, exitCode);
    }

    [TestMethod]
    public async Task RunAsync_WithIncludeGenerated_ReturnsSuccess()
    {
        string projectDir = CreateTestProject("""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net10.0</TargetFramework>
              </PropertyGroup>
            </Project>
            """, """
            // <auto-generated>
            public class GeneratedClass {
                public void GeneratedMethod() { }
            }
            """);

        int exitCode = await Program.RunAsync(["--target", projectDir, "--include-generated"]);

        Assert.AreEqual(0, exitCode);
    }

    private static string CreateTestProject(string csproj, string code)
    {
        string projectDir = Path.Combine(s_testRoot, Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(projectDir);

        File.WriteAllText(Path.Combine(projectDir, "TestProject.csproj"), csproj);
        File.WriteAllText(Path.Combine(projectDir, "Program.cs"), code);

        return projectDir;
    }
}
