namespace FindUnused;

/// <summary>
/// Configuration options for the analyzer
/// </summary>
public class AnalyzerConfiguration
{
    public bool IncludePublicSymbols { get; set; } = true;
    public bool IncludeInternalSymbols { get; set; } = true;
    public bool ExcludeGeneratedCode { get; set; } = true;

    /// <summary>
    /// Analysis mode: strict (fewer false positives) or loose (more comprehensive)
    /// </summary>
    public string AnalysisMode { get; set; } = "loose";

    /// <summary>
    /// Detect dead/unreachable code (experimental)
    /// </summary>
    public bool DetectDeadCode { get; set; } = false;

    /// <summary>
    /// Detect TODO/HACK/FIXME comments
    /// </summary>
    public bool DetectTodoComments { get; set; } = false;

    /// <summary>
    /// Patterns to exclude from analysis (e.g., NuGet packages, build outputs)
    /// </summary>
    public FrozenSet<string> ExclusionPatterns { get; init; } = FrozenSet.ToFrozenSet(
    [
        "/.nuget/packages/",
        "/.nuget/",
        "/packages/",
        "/bin/",
        "/obj/",
        "/debug/",
        "/release/"
    ], StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Markers indicating generated code
    /// </summary>
    public FrozenSet<string> GeneratedCodeMarkers { get; init; } = FrozenSet.ToFrozenSet(
    [
        "<auto-generated", "generated by", "<autogenerated",
        "// <auto-generated", "// This code generated by",
        "[GeneratedCode]", "@generated", "partial class",
        "[JsonSerializable]", "[CompilerGenerated]"
    ], StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Test framework attributes for identifying test methods
    /// </summary>
    public FrozenSet<string> TestAttributes { get; init; } = FrozenSet.ToFrozenSet(
    [
        "TestAttribute", "FactAttribute", "TheoryAttribute", "TestMethodAttribute",
        "TestCaseAttribute", "TestCaseSourceAttribute", "InlineDataAttribute",
        "ClassDataAttribute", "DynamicDataAttribute"
    ], StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Test class attributes
    /// </summary>
    public FrozenSet<string> TestClassAttributes { get; init; } = FrozenSet.ToFrozenSet(
    [
        "TestClassAttribute", "TestFixtureAttribute", "TestCategoryAttribute"
    ], StringComparer.OrdinalIgnoreCase);
}

/// <summary>
/// Cache for project analysis results
/// </summary>
public class ProjectAnalysisCache
{
    public Dictionary<ISymbol, HashSet<Location>> SymbolLocations { get; }
        = new Dictionary<ISymbol, HashSet<Location>>(SymbolEqualityComparer.Default);
}

/// <summary>
/// Intelligent caching system for analyzer performance.
/// Instance-based (per-analysis) to prevent unbounded growth across runs.
/// </summary>
public class AnalyzerCache
{
    private readonly Dictionary<ProjectId, ProjectAnalysisCache> _projectCaches = new();
    private const int MaxCacheEntries = 10000;
    
    public FrozenSet<string> ExclusionPatterns { get; }
    public FrozenSet<string> GeneratedCodeMarkers { get; }
    public FrozenSet<string> TestAttributes { get; }
    public FrozenSet<string> TestClassAttributes { get; }

    public AnalyzerCache(AnalyzerConfiguration? config = null)
    {
        var cfg = config ?? new AnalyzerConfiguration();
        ExclusionPatterns = cfg.ExclusionPatterns;
        GeneratedCodeMarkers = cfg.GeneratedCodeMarkers;
        TestAttributes = cfg.TestAttributes;
        TestClassAttributes = cfg.TestClassAttributes;
    }

    private ProjectAnalysisCache GetProjectCache(ProjectId projectId)
    {
        if (!_projectCaches.TryGetValue(projectId, out var cache))
        {
            cache = new ProjectAnalysisCache();
            _projectCaches[projectId] = cache;
        }
        return cache;
    }

    public async Task<HashSet<Location>> GetSymbolLocationsAsync(
        ISymbol symbol,
        ProjectId projectId,
        Solution solution,
        HashSet<ProjectId> solutionProjectIds,
        Func<Location, Solution, HashSet<ProjectId>, bool> isReferenceInSolutionSource)
    {
        var cache = GetProjectCache(projectId);
        if (cache.SymbolLocations.TryGetValue(symbol, out var locations))
            return locations;

        // Check cache size limit
        if (cache.SymbolLocations.Count >= MaxCacheEntries)
        {
            cache.SymbolLocations.Clear();
        }

        // Perform search and cache results
        locations = await PerformSymbolSearchAsync(symbol, solution, solutionProjectIds, isReferenceInSolutionSource);
        cache.SymbolLocations[symbol] = locations;
        return locations;
    }

    private static async Task<HashSet<Location>> PerformSymbolSearchAsync(
        ISymbol symbol,
        Solution solution,
        HashSet<ProjectId> solutionProjectIds,
        Func<Location, Solution, HashSet<ProjectId>, bool> isReferenceInSolutionSource
    )
    {
        var locations = new HashSet<Location>();
        var references = await SymbolFinder.FindReferencesAsync(symbol, solution);
        foreach (var rr in references)
        {
            foreach (var loc in rr.Locations)
            {
                if (isReferenceInSolutionSource(loc.Location, solution, solutionProjectIds))
                {
                    locations.Add(loc.Location);
                }
            }
        }
        return locations;
    }
}
